"""add token field for users

Revision ID: 262e8369a44a
Revises: adb7b52e5a99
Create Date: 2022-02-03 23:01:36.880304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262e8369a44a'
down_revision = 'adb7b52e5a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__follows__user_author'), 'follows', ['user', 'author'])
    op.create_unique_constraint(op.f('uq__ingredients__id'), 'ingredients', ['id'])
    op.create_unique_constraint(op.f('uq__recipe_ingredients__recipe_ingredient'), 'recipe_ingredients', ['recipe', 'ingredient'])
    op.create_unique_constraint(op.f('uq__recipe_tags__recipe_tag'), 'recipe_tags', ['recipe', 'tag'])
    op.create_unique_constraint(op.f('uq__tags__id'), 'tags', ['id'])
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_column('users', 'token')
    op.drop_constraint(op.f('uq__tags__id'), 'tags', type_='unique')
    op.drop_constraint(op.f('uq__recipe_tags__recipe_tag'), 'recipe_tags', type_='unique')
    op.drop_constraint(op.f('uq__recipe_ingredients__recipe_ingredient'), 'recipe_ingredients', type_='unique')
    op.drop_constraint(op.f('uq__ingredients__id'), 'ingredients', type_='unique')
    op.drop_constraint(op.f('uq__follows__user_author'), 'follows', type_='unique')
    # ### end Alembic commands ###
