"""create tables

Revision ID: adb7b52e5a99
Revises: 
Create Date: 2022-02-02 23:16:47.236336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb7b52e5a99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('measurement_unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__ingredients')),
    sa.UniqueConstraint('id', name=op.f('uq__ingredients__id'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tags')),
    sa.UniqueConstraint('id', name=op.f('uq__tags__id')),
    sa.UniqueConstraint('name', name=op.f('uq__tags__name'))
    )
    op.create_index(op.f('ix__tags__slug'), 'tags', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email')),
    sa.UniqueConstraint('id', name=op.f('uq__users__id'))
    )
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=True)
    op.create_table('follows',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name=op.f('fk__follows__author__users')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk__follows__user__users')),
    sa.PrimaryKeyConstraint('user', 'author', name=op.f('pk__follows')),
    sa.UniqueConstraint('user', 'author', name=op.f('uq__follows__user_author'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('cooking_time', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name=op.f('fk__recipes__author__users')),
    sa.PrimaryKeyConstraint('id', 'author', name=op.f('pk__recipes')),
    sa.UniqueConstraint('id', name=op.f('uq__recipes__id'))
    )
    op.create_table('favorited_recipes',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name=op.f('fk__favorited_recipes__recipe__recipes')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk__favorited_recipes__user__users')),
    sa.PrimaryKeyConstraint('user', 'recipe', name=op.f('pk__favorited_recipes')),
    sa.UniqueConstraint('recipe', 'user', name=op.f('uq__favorited_recipes__recipe_user'))
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredients.id'], name=op.f('fk__recipe_ingredients__ingredient__ingredients')),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name=op.f('fk__recipe_ingredients__recipe__recipes')),
    sa.PrimaryKeyConstraint('recipe', 'ingredient', name=op.f('pk__recipe_ingredients')),
    sa.UniqueConstraint('recipe', 'ingredient', name=op.f('uq__recipe_ingredients__recipe_ingredient'))
    )
    op.create_table('recipe_tags',
    sa.Column('recipe', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name=op.f('fk__recipe_tags__recipe__recipes')),
    sa.ForeignKeyConstraint(['tag'], ['tags.id'], name=op.f('fk__recipe_tags__tag__tags')),
    sa.PrimaryKeyConstraint('recipe', 'tag', name=op.f('pk__recipe_tags')),
    sa.UniqueConstraint('recipe', 'tag', name=op.f('uq__recipe_tags__recipe_tag'))
    )
    op.create_table('shopping_recipes',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name=op.f('fk__shopping_recipes__recipe__recipes')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk__shopping_recipes__user__users')),
    sa.PrimaryKeyConstraint('user', 'recipe', name=op.f('pk__shopping_recipes')),
    sa.UniqueConstraint('recipe', 'user', name=op.f('uq__shopping_recipes__recipe_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_recipes')
    op.drop_table('recipe_tags')
    op.drop_table('recipe_ingredients')
    op.drop_table('favorited_recipes')
    op.drop_table('recipes')
    op.drop_table('follows')
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix__tags__slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
